language: python
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '3.5'
- '3.6'
install:
- pip install -e .
- pip list
script: skip
jobs:
  include:
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: tmbo
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "VgiusCOC6cfjU+2yyhcWnEu/Tk1/FqYnApNuexIZWMGBod0l58qb0K8RUJvR7qz4E5jrQ3iMBi2HSDqPEKAX9tTMdadyGWOuSKckrIZO1EiWbTvjRQGc/og57LaUfGazfomOAVGjj3hNLjrHjija5sY3BVFsdzylME81jvLmqm8Ssqe1B1BdRsw1q5k1Ebl7uAjkeeGZl0C/P2ZMv2GFtRAfwkUb6cBpjDBNU7+asSiFSQ+1lG6X5NsvdoVPAEBkAhmwjOC2caCFuy2X73URxPlrd3RnkvTvOwGMEDuJaXHzJBd4pQZwonyuOZMQRsH+QH4acKzoW1Rh0fLyRBe2Xcvl9Op0IKka5Sj16B4bD26BVM1/Jva2FdlRh45FerPVuScxud/FxAa+NGC6rw0cIJd6xDDyoaI50od0CZMDX4MITILhckyeWzFyYELzgA9vx8wQJ3JSqSDfhzYMsEzEkvWTfNgPSm7NDVSPJW7NchLE4oRKRjlXyvMPzu6z83ESC6edVrktTwLuPRUUPMYsZ+PO2gty87rlBi7WMCkgysNEI2ypc6fSFukE2cOdTDUX/E/W1vXxXdlClO81414FKrpSe208kch8C34BxFA2BSW6yfT7dZOnF7Xas304sSvK4GvAXF3O6P7AEHOkGhpaf0MW4w+7XV8lFry4LRfNGaA="
